apiVersion: apps/v1
kind: Deployment
metadata:
  name: spam2000
  labels:
    app.kubernetes.io/name: spam2000
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: spam2000
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spam2000
    spec:
      containers:
        - name: spam2000
          image: >-
            {{- if .Values.image.digest -}}
            {{ printf "%s@%s" .Values.image.repository .Values.image.digest }}
            {{- else -}}
            {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
            {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}