apiVersion: v1
kind: Service
metadata:
  name: spam2000
  labels:
    app.kubernetes.io/name: spam2000
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: spam2000
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http